// _DM2_PreferencesPref_EOArchive_English.java
// Generated by EnterpriseObjects palette at Tuesday, December 25, 2007 2:57:49 AM America/New_York

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _DM2_PreferencesPref_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1, _iBHelpConnector10, _iBHelpConnector11, _iBHelpConnector12, _iBHelpConnector13, _iBHelpConnector14, _iBHelpConnector15, _iBHelpConnector16, _iBHelpConnector2, _iBHelpConnector3, _iBHelpConnector4, _iBHelpConnector5, _iBHelpConnector6, _iBHelpConnector7, _iBHelpConnector8, _iBHelpConnector9;
    Updater _updater0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1, _eoFrame2;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0, _nsImageView1, _nsImageView2;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsProgressIndicator0, _nsProgressIndicator1, _nsView0, _nsView1, _nsView2, _nsView3, _nsView4, _nsView5, _nsView6, _nsView7, _nsView8;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton10, _nsButton11, _nsButton12, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8, _nsButton9;
    javax.swing.JCheckBox _nsButton13, _nsButton14, _nsButton15, _nsButton16, _nsButton17, _nsButton18, _nsButton19, _nsButton20, _nsButton21, _nsButton22, _nsButton23, _nsButton24, _nsButton25, _nsButton26;
    javax.swing.JComboBox _popup0, _popup1, _popup2, _popup3, _popup4, _popup5, _popup6, _popup7, _popup8;
    javax.swing.JPanel _nsView10, _nsView11, _nsView9;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1, _jRadioButton2;
    javax.swing.JTabbedPane _nsTabView0;

    public _DM2_PreferencesPref_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _iBHelpConnector16 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector15 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector14 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsImageView2 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsButton12 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "helpButton")) != null)) {
            _nsButton11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton11");
        } else {
            _nsButton11 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton5");
        }

        _iBHelpConnector13 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton10 = (javax.swing.JButton)_registered(new javax.swing.JButton("Register PRO"), "NSButton2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "contactAuthorButton")) != null)) {
            _nsButton9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton9");
        } else {
            _nsButton9 = (javax.swing.JButton)_registered(new javax.swing.JButton("Contact Author"), "NSButton1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "visitHomepageButton")) != null)) {
            _nsButton8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton8");
        } else {
            _nsButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton("Visit Homepage"), "NSButton");
        }

        _nsImageView1 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "readmeTextView")) != null)) {
            _nsTextView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView0");
        } else {
            _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        }

        _nsView8 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "osWarningTextField")) != null)) {
            _nsTextField14 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField14");
        } else {
            _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        }

        _nsView7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _jRadioButton2 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Flash on \u00bc note only"), "");
        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("32nd Notes"), "");
        _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("16th Notes"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "midiClockResolutionMatrix")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(3, 1, 4, 2), "NSMatrix1");
        }

        _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsView6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "growlSupportCheckbox")) != null)) {
            _nsButton7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton7");
        } else {
            _nsButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton("Save To..."), "NSButton");
        }

        _nsView5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank4WhoControlsLEDsPopUpButton")) != null)) {
            _popup8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup8");
        } else {
            _popup8 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank4ScratchRingBumpIgnorePopUpButton")) != null)) {
            _popup7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup7");
        } else {
            _popup7 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank4DisplaysMIDIClockCheckbox")) != null)) {
            _nsButton26 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton26");
        } else {
            _nsButton26 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Displays MIDI Clock"), "NSButton42");
        }

        _iBHelpConnector12 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank4InvertLedsCheckbox")) != null)) {
            _nsButton25 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton25");
        } else {
            _nsButton25 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Invert LEDs"), "NSButton41");
        }

        _iBHelpConnector11 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank4StickyButtonsCheckbox")) != null)) {
            _nsButton24 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton24");
        } else {
            _nsButton24 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Sticky Buttons"), "NSButton4");
        }

        _nsView4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank3WhoControlsLEDsPopUpButton")) != null)) {
            _popup6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup6");
        } else {
            _popup6 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank3ScratchRingBumpIgnorePopUpButton")) != null)) {
            _popup5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup5");
        } else {
            _popup5 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank3DisplaysMIDIClockCheckbox")) != null)) {
            _nsButton23 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton23");
        } else {
            _nsButton23 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Displays MIDI Clock"), "NSButton42");
        }

        _iBHelpConnector10 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank3InvertLedsCheckbox")) != null)) {
            _nsButton22 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton22");
        } else {
            _nsButton22 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Invert LEDs"), "NSButton41");
        }

        _iBHelpConnector9 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank3StickyButtonsCheckbox")) != null)) {
            _nsButton21 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton21");
        } else {
            _nsButton21 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Sticky Buttons"), "NSButton4");
        }

        _nsView3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank2WhoControlsLEDsPopUpButton")) != null)) {
            _popup4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup4");
        } else {
            _popup4 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank2ScratchRingBumpIgnorePopUpButton")) != null)) {
            _popup3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup3");
        } else {
            _popup3 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank2DisplaysMIDIClockCheckbox")) != null)) {
            _nsButton20 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton20");
        } else {
            _nsButton20 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Displays MIDI Clock"), "NSButton42");
        }

        _iBHelpConnector8 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank2InvertLedsCheckbox")) != null)) {
            _nsButton19 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton19");
        } else {
            _nsButton19 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Invert LEDs"), "NSButton41");
        }

        _iBHelpConnector7 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank2StickyButtonsCheckbox")) != null)) {
            _nsButton18 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton18");
        } else {
            _nsButton18 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Sticky Buttons"), "NSButton4");
        }

        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank1DisplaysMIDIClockCheckbox")) != null)) {
            _nsButton17 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton17");
        } else {
            _nsButton17 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Displays MIDI Clock"), "NSButton42");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank1WhoControlsLEDsPopUpButton")) != null)) {
            _popup2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup2");
        } else {
            _popup2 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank1ScratchRingBumpIgnorePopUpButton")) != null)) {
            _popup1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup1");
        } else {
            _popup1 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        _iBHelpConnector6 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank1InvertLedsCheckbox")) != null)) {
            _nsButton16 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton16");
        } else {
            _nsButton16 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Invert LEDs"), "NSButton41");
        }

        _iBHelpConnector5 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bank1StickyButtonsCheckbox")) != null)) {
            _nsButton15 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton15");
        } else {
            _nsButton15 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Sticky Buttons"), "NSButton4");
        }

        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _iBHelpConnector4 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton14 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Growl Support"), "NSButton41");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton");
        _eoFrame2 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel");
        _nsView11 = (JPanel)_eoFrame2.getContentPane();
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsProgressIndicator1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "1");
        _updater0 = (Updater)_registered(new Updater(), "Updater");
        _nsProgressIndicator0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "11");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "resetInterface")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("Reset Interface"), "NSButton3");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkForUpdateButton")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("Check for Update"), "NSButton2");
        }

        _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _iBHelpConnector3 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkAutomaticallyCheckbox")) != null)) {
            _nsButton13 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton13");
        } else {
            _nsButton13 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Check Automatically"), "NSButton4");
        }

        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _iBHelpConnector2 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "softwareModeButton")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "clearLEDsButton")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("Clear LEDs"), "NSButton1");
        }

        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "resetCalibrationButton")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Reset Calibration"), "NSButton");
        }

        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tabView")) != null)) {
            _nsTabView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JTabbedPane)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTabView0");
        } else {
            _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "NSTabView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "saveButton")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Save"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "_window")) != null)) {
            _eoFrame1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame1");
        } else {
            _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "PrefPane");
        }

        _nsView10 = (JPanel)_eoFrame1.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "registerButton")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Register"), "NSButton");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "RegisterPanel");
        _nsView9 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "registerButton");
        }

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _connect(_owner(), _nsButton11, "helpButton");
        }

        _nsButton11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "helpButtonClicked", _nsButton11), ""));

        if (_replacedObjects.objectForKey("_nsTabView0") == null) {
            _connect(_owner(), _nsTabView0, "tabView");
        }

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _connect(_owner(), _nsButton9, "contactAuthorButton");
        }

        _nsButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "contactAuthorButtonClicked", _nsButton9), ""));

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _connect(_owner(), _nsButton8, "visitHomepageButton");
        }

        _nsButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "visitHomepageButtonClicked", _nsButton8), ""));

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_owner(), _nsTextView0, "readmeTextView");
        }

        if (_replacedObjects.objectForKey("_nsTextField14") == null) {
            _connect(_owner(), _nsTextField14, "osWarningTextField");
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "midiClockResolutionMatrix");
        }

        _jRadioButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "midiClockResolutionMatrixChanged", _jRadioButton0), ""));
        _jRadioButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "midiClockResolutionMatrixChanged", _jRadioButton1), ""));
        _jRadioButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "midiClockResolutionMatrixChanged", _jRadioButton2), ""));

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _connect(_owner(), _nsButton7, "growlSupportCheckbox");
        }

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _connect(_owner(), _nsButton7, "exportTraktorButton");
        }

        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "exportTraktorButtonClicked", _nsButton7), ""));

        if (_replacedObjects.objectForKey("_popup8") == null) {
            _connect(_owner(), _popup8, "bank4WhoControlsLEDsPopUpButton");
        }

        _popup8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "whoControlsLEDsPopUpButtonChanged", _popup8), ""));

        if (_replacedObjects.objectForKey("_popup8") == null) {
            _popup8.setModel(new javax.swing.DefaultComboBoxModel());
            _popup8.addItem("Driver Only");
            _popup8.addItem("MIDI Messages Only");
            _popup8.addItem("Driver & MIDI Messages");
        }

        if (_replacedObjects.objectForKey("_popup7") == null) {
            _connect(_owner(), _popup7, "bank4ScratchRingBumpIgnorePopUpButton");
        }

        _popup7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "scratchRingBumpIgnorePopUpButtonChanged", _popup7), ""));

        if (_replacedObjects.objectForKey("_popup7") == null) {
            _popup7.setModel(new javax.swing.DefaultComboBoxModel());
            _popup7.addItem("Off");
            _popup7.addItem("1");
            _popup7.addItem("2");
            _popup7.addItem("3");
            _popup7.addItem("4");
            _popup7.addItem("5");
            _popup7.addItem("6");
            _popup7.addItem("7");
            _popup7.addItem("8");
            _popup7.addItem("9");
            _popup7.addItem("10");
        }

        if (_replacedObjects.objectForKey("_nsButton26") == null) {
            _connect(_owner(), _nsButton26, "bank4DisplaysMIDIClockCheckbox");
        }

        _nsButton26.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "displaysMIDIClockCheckboxClicked", _nsButton26), ""));

        if (_replacedObjects.objectForKey("_nsButton25") == null) {
            _connect(_owner(), _nsButton25, "bank4InvertLedsCheckbox");
        }

        _nsButton25.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "bank4InvertLedsCheckboxClicked", _nsButton25), ""));

        if (_replacedObjects.objectForKey("_nsButton24") == null) {
            _connect(_owner(), _nsButton24, "bank4StickyButtonsCheckbox");
        }

        _nsButton24.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "bank4StickyButtonsCheckboxClicked", _nsButton24), ""));

        if (_replacedObjects.objectForKey("_popup6") == null) {
            _connect(_owner(), _popup6, "bank3WhoControlsLEDsPopUpButton");
        }

        _popup6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "whoControlsLEDsPopUpButtonChanged", _popup6), ""));

        if (_replacedObjects.objectForKey("_popup6") == null) {
            _popup6.setModel(new javax.swing.DefaultComboBoxModel());
            _popup6.addItem("Driver Only");
            _popup6.addItem("MIDI Messages Only");
            _popup6.addItem("Driver & MIDI Messages");
        }

        if (_replacedObjects.objectForKey("_popup5") == null) {
            _connect(_owner(), _popup5, "bank3ScratchRingBumpIgnorePopUpButton");
        }

        _popup5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "scratchRingBumpIgnorePopUpButtonChanged", _popup5), ""));

        if (_replacedObjects.objectForKey("_popup5") == null) {
            _popup5.setModel(new javax.swing.DefaultComboBoxModel());
            _popup5.addItem("Off");
            _popup5.addItem("1");
            _popup5.addItem("2");
            _popup5.addItem("3");
            _popup5.addItem("4");
            _popup5.addItem("5");
            _popup5.addItem("6");
            _popup5.addItem("7");
            _popup5.addItem("8");
            _popup5.addItem("9");
            _popup5.addItem("10");
        }

        if (_replacedObjects.objectForKey("_nsButton23") == null) {
            _connect(_owner(), _nsButton23, "bank3DisplaysMIDIClockCheckbox");
        }

        _nsButton23.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "displaysMIDIClockCheckboxClicked", _nsButton23), ""));

        if (_replacedObjects.objectForKey("_nsButton22") == null) {
            _connect(_owner(), _nsButton22, "bank3InvertLedsCheckbox");
        }

        _nsButton22.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "bank3InvertLedsCheckboxClicked", _nsButton22), ""));

        if (_replacedObjects.objectForKey("_nsButton21") == null) {
            _connect(_owner(), _nsButton21, "bank3StickyButtonsCheckbox");
        }

        _nsButton21.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "bank3StickyButtonsCheckboxClicked", _nsButton21), ""));

        if (_replacedObjects.objectForKey("_popup4") == null) {
            _connect(_owner(), _popup4, "bank2WhoControlsLEDsPopUpButton");
        }

        _popup4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "whoControlsLEDsPopUpButtonChanged", _popup4), ""));

        if (_replacedObjects.objectForKey("_popup4") == null) {
            _popup4.setModel(new javax.swing.DefaultComboBoxModel());
            _popup4.addItem("Driver Only");
            _popup4.addItem("MIDI Messages Only");
            _popup4.addItem("Driver & MIDI Messages");
        }

        if (_replacedObjects.objectForKey("_popup3") == null) {
            _connect(_owner(), _popup3, "bank2ScratchRingBumpIgnorePopUpButton");
        }

        _popup3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "scratchRingBumpIgnorePopUpButtonChanged", _popup3), ""));

        if (_replacedObjects.objectForKey("_popup3") == null) {
            _popup3.setModel(new javax.swing.DefaultComboBoxModel());
            _popup3.addItem("Off");
            _popup3.addItem("1");
            _popup3.addItem("2");
            _popup3.addItem("3");
            _popup3.addItem("4");
            _popup3.addItem("5");
            _popup3.addItem("6");
            _popup3.addItem("7");
            _popup3.addItem("8");
            _popup3.addItem("9");
            _popup3.addItem("10");
        }

        if (_replacedObjects.objectForKey("_nsButton20") == null) {
            _connect(_owner(), _nsButton20, "bank2DisplaysMIDIClockCheckbox");
        }

        _nsButton20.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "displaysMIDIClockCheckboxClicked", _nsButton20), ""));

        if (_replacedObjects.objectForKey("_nsButton19") == null) {
            _connect(_owner(), _nsButton19, "bank2InvertLedsCheckbox");
        }

        _nsButton19.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "bank2InvertLedsCheckboxClicked", _nsButton19), ""));

        if (_replacedObjects.objectForKey("_nsButton18") == null) {
            _connect(_owner(), _nsButton18, "bank2StickyButtonsCheckbox");
        }

        _nsButton18.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "bank2StickyButtonsCheckboxClicked", _nsButton18), ""));

        if (_replacedObjects.objectForKey("_nsButton17") == null) {
            _connect(_owner(), _nsButton17, "bank1DisplaysMIDIClockCheckbox");
        }

        _nsButton17.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "displaysMIDIClockCheckboxClicked", _nsButton17), ""));

        if (_replacedObjects.objectForKey("_popup2") == null) {
            _connect(_owner(), _popup2, "bank1WhoControlsLEDsPopUpButton");
        }

        _popup2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "whoControlsLEDsPopUpButtonChanged", _popup2), ""));

        if (_replacedObjects.objectForKey("_popup2") == null) {
            _popup2.setModel(new javax.swing.DefaultComboBoxModel());
            _popup2.addItem("Driver Only");
            _popup2.addItem("MIDI Messages Only");
            _popup2.addItem("Driver & MIDI Messages");
        }

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _connect(_owner(), _popup1, "bank1ScratchRingBumpIgnorePopUpButton");
        }

        _popup1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "scratchRingBumpIgnorePopUpButtonChanged", _popup1), ""));

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _popup1.setModel(new javax.swing.DefaultComboBoxModel());
            _popup1.addItem("Off");
            _popup1.addItem("1");
            _popup1.addItem("2");
            _popup1.addItem("3");
            _popup1.addItem("4");
            _popup1.addItem("5");
            _popup1.addItem("6");
            _popup1.addItem("7");
            _popup1.addItem("8");
            _popup1.addItem("9");
            _popup1.addItem("10");
        }

        if (_replacedObjects.objectForKey("_nsButton16") == null) {
            _connect(_owner(), _nsButton16, "bank1InvertLedsCheckbox");
        }

        _nsButton16.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "bank1InvertLedsCheckboxClicked", _nsButton16), ""));

        if (_replacedObjects.objectForKey("_nsButton15") == null) {
            _connect(_owner(), _nsButton15, "bank1StickyButtonsCheckbox");
        }

        _nsButton15.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "bank1StickyButtonsCheckboxClicked", _nsButton15), ""));
        _nsButton14.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "growlSupportCheckboxClicked", _nsButton14), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "resetInterface");
        }

        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "resetInterfaceButtonClicked", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "checkForUpdateButton");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "checkForUpdateButtonClicked", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsButton13") == null) {
            _connect(_owner(), _nsButton13, "checkAutomaticallyCheckbox");
        }

        _nsButton13.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "checkAutomaticallyCheckboxClicked", _nsButton13), ""));

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "softwareModeButton");
        }

        _popup0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "softwareModeComboBoxChanged", _popup0), ""));

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Generic MIDI");
            _popup0.addItem("Mixxx");
            _popup0.addItem("Traktor");
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "clearLEDsButton");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "clearLEDsButtonClicked", _nsButton3), ""));

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "resetCalibrationButton");
        }

        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "resetCalibrationButtonClicked", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "saveButton");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "saveButtonClicked", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _connect(_owner(), _eoFrame1, "_window");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "registerButtonClicked", _nsButton0), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField15, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField15.setEditable(false);
        _nsTextField15.setOpaque(false);
        _nsTextField15.setText("Drag and Drop license file into the box.\n");
        _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField15.setSelectable(false);
        _nsTextField15.setEnabled(true);
        _nsTextField15.setBorder(null);
        _nsButton12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_eoFrame0, "performClose", _nsButton12), ""));
        _setFontForComponent(_nsButton12, "Lucida Grande", 13, Font.PLAIN);
        _nsButton12.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _setFontForComponent(_nsButton11, "Lucida Grande", 13, Font.PLAIN);
            _nsButton11.setMargin(new Insets(0, 2, 0, 2));
        }

        _nsButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_eoFrame0, "makeKeyAndOrderFront", _nsButton10), ""));
        _setFontForComponent(_nsButton10, "Lucida Grande", 13, Font.PLAIN);
        _nsButton10.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _setFontForComponent(_nsButton9, "Lucida Grande", 13, Font.PLAIN);
            _nsButton9.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _setFontForComponent(_nsButton8, "Lucida Grande", 13, Font.PLAIN);
            _nsButton8.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _nsTextView0.setEditable(false);
            _nsTextView0.setOpaque(true);
            _nsTextView0.setText("");
        }

        if (!(_nsView8.getLayout() instanceof EOViewLayout)) { _nsView8.setLayout(new EOViewLayout()); }
        _nsTextView0.setSize(372, 242);
        _nsTextView0.setLocation(173, 20);
        ((EOViewLayout)_nsView8.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.MinYMargin);
        _nsView8.add(_nsTextView0);
        _nsImageView1.setSize(128, 128);
        _nsImageView1.setLocation(20, 20);
        ((EOViewLayout)_nsView8.getLayout()).setAutosizingMask(_nsImageView1, EOViewLayout.MinYMargin);
        _nsView8.add(_nsImageView1);
        _nsButton8.setSize(133, 26);
        _nsButton8.setLocation(19, 208);
        ((EOViewLayout)_nsView8.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinYMargin);
        _nsView8.add(_nsButton8);
        _nsButton9.setSize(133, 26);
        _nsButton9.setLocation(19, 240);
        ((EOViewLayout)_nsView8.getLayout()).setAutosizingMask(_nsButton9, EOViewLayout.MinYMargin);
        _nsView8.add(_nsButton9);
        _nsButton10.setSize(133, 26);
        _nsButton10.setLocation(19, 176);
        ((EOViewLayout)_nsView8.getLayout()).setAutosizingMask(_nsButton10, EOViewLayout.MinYMargin);
        _nsView8.add(_nsButton10);
        _nsTextField3.setSize(134, 17);
        _nsTextField3.setLocation(18, 153);
        ((EOViewLayout)_nsView8.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView8.add(_nsTextField3);

        if (_replacedObjects.objectForKey("_nsTextField14") == null) {
            _setFontForComponent(_nsTextField14, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField14.setEditable(false);
            _nsTextField14.setOpaque(false);
            _nsTextField14.setText("Only available in OS X 10.4 or greater.\n");
            _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField14.setSelectable(false);
            _nsTextField14.setEnabled(true);
            _nsTextField14.setBorder(null);
        }

        if (!(_nsView7.getLayout() instanceof EOViewLayout)) { _nsView7.setLayout(new EOViewLayout()); }
        _nsTextField14.setSize(511, 22);
        _nsTextField14.setLocation(18, 110);
        ((EOViewLayout)_nsView7.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.MinYMargin);
        _nsView7.add(_nsTextField14);
        _setFontForComponent(_jRadioButton2, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jRadioButton0.setSize(166, 17);
            _jRadioButton0.setLocation(0, 0);
            _nsMatrix0.add(_jRadioButton0);
            _jRadioButton1.setSize(166, 17);
            _jRadioButton1.setLocation(0, 20);
            _nsMatrix0.add(_jRadioButton1);
            _jRadioButton2.setSize(166, 17);
            _jRadioButton2.setLocation(0, 40);
            _nsMatrix0.add(_jRadioButton2);
            _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField13, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField13.setEditable(false);
        _nsTextField13.setOpaque(false);
        _nsTextField13.setText("MIDI Clock Display\n");
        _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField13.setSelectable(false);
        _nsTextField13.setEnabled(true);
        _nsTextField13.setBorder(null);
        if (!(_nsView6.getLayout() instanceof EOViewLayout)) { _nsView6.setLayout(new EOViewLayout()); }
        _nsTextField13.setSize(129, 17);
        _nsTextField13.setLocation(18, 20);
        ((EOViewLayout)_nsView6.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MinYMargin);
        _nsView6.add(_nsTextField13);
        _nsMatrix0.setSize(167, 58);
        _nsMatrix0.setLocation(30, 44);
        ((EOViewLayout)_nsView6.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView6.add(_nsMatrix0);
        _setFontForComponent(_nsTextField12, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField12.setEditable(false);
        _nsTextField12.setOpaque(false);
        _nsTextField12.setText("Export Traktor .tks file\n");
        _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField12.setSelectable(false);
        _nsTextField12.setEnabled(true);
        _nsTextField12.setBorder(null);

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _setFontForComponent(_nsButton7, "Lucida Grande", 13, Font.PLAIN);
            _nsButton7.setMargin(new Insets(0, 2, 0, 2));
        }

        if (!(_nsView5.getLayout() instanceof EOViewLayout)) { _nsView5.setLayout(new EOViewLayout()); }
        _nsButton7.setSize(94, 26);
        _nsButton7.setLocation(48, 240);
        ((EOViewLayout)_nsView5.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinYMargin);
        _nsView5.add(_nsButton7);
        _nsTextField12.setSize(118, 13);
        _nsTextField12.setLocation(21, 223);
        ((EOViewLayout)_nsView5.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MinYMargin);
        _nsView5.add(_nsTextField12);

        if (_replacedObjects.objectForKey("_popup8") == null) {
            _setFontForComponent(_popup8, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_popup7") == null) {
            _setFontForComponent(_popup7, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField11, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField11.setEditable(false);
        _nsTextField11.setOpaque(false);
        _nsTextField11.setText("Who controls LEDs\n");
        _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField11.setSelectable(false);
        _nsTextField11.setEnabled(true);
        _nsTextField11.setBorder(null);
        _setFontForComponent(_nsTextField10, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("Scratch Ring Bump Ignore\n");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);

        if (_replacedObjects.objectForKey("_nsButton26") == null) {
            _setFontForComponent(_nsButton26, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton25") == null) {
            _setFontForComponent(_nsButton25, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton24") == null) {
            _setFontForComponent(_nsButton24, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsView4.getLayout() instanceof EOViewLayout)) { _nsView4.setLayout(new EOViewLayout()); }
        _nsButton24.setSize(111, 17);
        _nsButton24.setLocation(18, 19);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsButton24, EOViewLayout.MinYMargin);
        _nsView4.add(_nsButton24);
        _nsButton25.setSize(93, 17);
        _nsButton25.setLocation(18, 39);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsButton25, EOViewLayout.MinYMargin);
        _nsView4.add(_nsButton25);
        _nsButton26.setSize(147, 17);
        _nsButton26.setLocation(18, 59);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsButton26, EOViewLayout.MinYMargin);
        _nsView4.add(_nsButton26);
        _nsTextField10.setSize(143, 13);
        _nsTextField10.setLocation(383, 20);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
        _nsView4.add(_nsTextField10);
        _nsTextField11.setSize(136, 13);
        _nsTextField11.setLocation(390, 69);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
        _nsView4.add(_nsTextField11);
        _popup7.setSize(123, 26);
        _popup7.setLocation(403, 38);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_popup7, EOViewLayout.MinYMargin);
        _nsView4.add(_popup7);
        _popup8.setSize(123, 26);
        _popup8.setLocation(403, 88);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_popup8, EOViewLayout.MinYMargin);
        _nsView4.add(_popup8);

        if (_replacedObjects.objectForKey("_popup6") == null) {
            _setFontForComponent(_popup6, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_popup5") == null) {
            _setFontForComponent(_popup5, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField9, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField9.setEditable(false);
        _nsTextField9.setOpaque(false);
        _nsTextField9.setText("Who controls LEDs\n");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField9.setSelectable(false);
        _nsTextField9.setEnabled(true);
        _nsTextField9.setBorder(null);
        _setFontForComponent(_nsTextField8, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("Scratch Ring Bump Ignore\n");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);

        if (_replacedObjects.objectForKey("_nsButton23") == null) {
            _setFontForComponent(_nsButton23, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton22") == null) {
            _setFontForComponent(_nsButton22, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton21") == null) {
            _setFontForComponent(_nsButton21, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsButton21.setSize(111, 17);
        _nsButton21.setLocation(18, 19);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton21, EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton21);
        _nsButton22.setSize(93, 17);
        _nsButton22.setLocation(18, 39);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton22, EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton22);
        _nsButton23.setSize(147, 17);
        _nsButton23.setLocation(18, 59);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton23, EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton23);
        _nsTextField8.setSize(143, 13);
        _nsTextField8.setLocation(383, 20);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField8);
        _nsTextField9.setSize(136, 13);
        _nsTextField9.setLocation(390, 69);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField9);
        _popup5.setSize(123, 26);
        _popup5.setLocation(403, 38);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_popup5, EOViewLayout.MinYMargin);
        _nsView3.add(_popup5);
        _popup6.setSize(123, 26);
        _popup6.setLocation(403, 88);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_popup6, EOViewLayout.MinYMargin);
        _nsView3.add(_popup6);

        if (_replacedObjects.objectForKey("_popup4") == null) {
            _setFontForComponent(_popup4, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_popup3") == null) {
            _setFontForComponent(_popup3, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField7, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Who controls LEDs\n");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Scratch Ring Bump Ignore\n");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);

        if (_replacedObjects.objectForKey("_nsButton20") == null) {
            _setFontForComponent(_nsButton20, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton19") == null) {
            _setFontForComponent(_nsButton19, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton18") == null) {
            _setFontForComponent(_nsButton18, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsButton18.setSize(111, 17);
        _nsButton18.setLocation(18, 19);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton18, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton18);
        _nsButton19.setSize(93, 17);
        _nsButton19.setLocation(18, 39);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton19, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton19);
        _nsButton20.setSize(147, 17);
        _nsButton20.setLocation(18, 59);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton20, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton20);
        _nsTextField6.setSize(143, 13);
        _nsTextField6.setLocation(383, 20);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField6);
        _nsTextField7.setSize(136, 13);
        _nsTextField7.setLocation(390, 69);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField7);
        _popup3.setSize(123, 26);
        _popup3.setLocation(403, 38);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_popup3, EOViewLayout.MinYMargin);
        _nsView2.add(_popup3);
        _popup4.setSize(123, 26);
        _popup4.setLocation(403, 88);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_popup4, EOViewLayout.MinYMargin);
        _nsView2.add(_popup4);

        if (_replacedObjects.objectForKey("_nsButton17") == null) {
            _setFontForComponent(_nsButton17, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_popup2") == null) {
            _setFontForComponent(_popup2, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _setFontForComponent(_popup1, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField5, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("Who controls LEDs\n");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        _setFontForComponent(_nsTextField4, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Scratch Ring Bump Ignore\n");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);

        if (_replacedObjects.objectForKey("_nsButton16") == null) {
            _setFontForComponent(_nsButton16, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton15") == null) {
            _setFontForComponent(_nsButton15, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsButton15.setSize(111, 17);
        _nsButton15.setLocation(18, 19);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton15, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton15);
        _nsButton16.setSize(93, 17);
        _nsButton16.setLocation(18, 39);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton16, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton16);
        _nsTextField4.setSize(143, 13);
        _nsTextField4.setLocation(383, 20);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField4);
        _nsTextField5.setSize(136, 13);
        _nsTextField5.setLocation(390, 69);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField5);
        _popup1.setSize(123, 26);
        _popup1.setLocation(403, 38);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_popup1, EOViewLayout.MinYMargin);
        _nsView1.add(_popup1);
        _popup2.setSize(123, 26);
        _popup2.setLocation(403, 88);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_popup2, EOViewLayout.MinYMargin);
        _nsView1.add(_popup2);
        _nsButton17.setSize(147, 17);
        _nsButton17.setLocation(18, 59);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton17, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton17);
        _setFontForComponent(_nsButton14, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("Version Beta 3\n");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _connect(_updater0, _nsTextField3, "versionField");
        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_updater0, "cancelUpdate", _nsButton6), ""));
        _setFontForComponent(_nsButton6, "Lucida Grande", 13, Font.PLAIN);
        _nsButton6.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsView11.getLayout() instanceof EOViewLayout)) { _nsView11.setLayout(new EOViewLayout()); }
        _nsProgressIndicator1.setSize(216, 20);
        _nsProgressIndicator1.setLocation(11, 39);
        ((EOViewLayout)_nsView11.getLayout()).setAutosizingMask(_nsProgressIndicator1, EOViewLayout.MinYMargin);
        _nsView11.add(_nsProgressIndicator1);
        _nsTextField2.setSize(218, 17);
        _nsTextField2.setLocation(11, 14);
        ((EOViewLayout)_nsView11.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView11.add(_nsTextField2);
        _nsButton6.setSize(75, 26);
        _nsButton6.setLocation(154, 73);
        ((EOViewLayout)_nsView11.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
        _nsView11.add(_nsButton6);
        _nsView11.setSize(238, 115);
        _eoFrame2.setTitle("");
        _eoFrame2.setLocation(1274, 453);
        _eoFrame2.setSize(238, 115);
        _connect(_updater0, _eoFrame2, "progressPanel");
        _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Update field");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _connect(_updater0, _nsTextField2, "progressField");
        _connect(_updater0, _nsProgressIndicator1, "progressIndicator");
        _connect(_updater0, _nsProgressIndicator0, "checkProgressInidicator");

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
            _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
            _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton13") == null) {
            _setFontForComponent(_nsButton13, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Software Mode\n");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 13, Font.PLAIN);
            _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsButton2.setSize(141, 26);
        _nsButton2.setLocation(19, 50);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton2);
        _nsButton3.setSize(100, 26);
        _nsButton3.setLocation(19, 18);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton3);
        _popup0.setSize(135, 26);
        _popup0.setLocation(22, 103);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsTextField1.setSize(114, 17);
        _nsTextField1.setLocation(18, 80);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsButton13.setSize(151, 17);
        _nsButton13.setLocation(162, 244);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton13, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton13);
        _nsImageView0.setSize(315, 174);
        _nsImageView0.setLocation(230, 63);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsImageView0);
        _nsButton4.setSize(141, 26);
        _nsButton4.setLocation(19, 240);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton4);
        _nsButton5.setSize(141, 26);
        _nsButton5.setLocation(19, 208);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton5);
        _nsProgressIndicator0.setSize(16, 16);
        _nsProgressIndicator0.setLocation(0, 244);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsProgressIndicator0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsProgressIndicator0);
        _nsButton14.setSize(113, 17);
        _nsButton14.setLocation(18, 142);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton14, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton14);

        if (_replacedObjects.objectForKey("_nsTabView0") == null) {
            _nsTabView0.addTab("Global", _nsView0);
            _nsTabView0.addTab("Bank 1", _nsView1);
            _nsTabView0.addTab("Bank 2", _nsView2);
            _nsTabView0.addTab("Bank 3", _nsView3);
            _nsTabView0.addTab("Bank 4", _nsView4);
            _nsTabView0.addTab("Traktor", _nsView5);
            _nsTabView0.addTab("Advanced", _nsView6);
            _nsTabView0.addTab("Status", _nsView7);
            _nsTabView0.addTab("About", _nsView8);
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        if (!(_nsView10.getLayout() instanceof EOViewLayout)) { _nsView10.setLayout(new EOViewLayout()); }
        _nsButton1.setSize(60, 26);
        _nsButton1.setLocation(12, 328);
        ((EOViewLayout)_nsView10.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView10.add(_nsButton1);
        _nsTabView0.setSize(555, 322);
        _nsTabView0.setLocation(11, 5);
        ((EOViewLayout)_nsView10.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.MinYMargin);
        _nsView10.add(_nsTabView0);
        _nsButton11.setSize(21, 23);
        _nsButton11.setLocation(543, 330);
        ((EOViewLayout)_nsView10.getLayout()).setAutosizingMask(_nsButton11, EOViewLayout.MinYMargin);
        _nsView10.add(_nsButton11);

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _nsView10.setSize(577, 362);
            _eoFrame1.setTitle("<< do not localize >>");
            _eoFrame1.setLocation(625, 143);
            _eoFrame1.setSize(577, 362);
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Visit http://www.joemattiello.com/dm2/pro.html\nfor information about the pro version and to purchase a license.");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView9.getLayout() instanceof EOViewLayout)) { _nsView9.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(326, 54);
        _nsTextField0.setLocation(11, 14);
        ((EOViewLayout)_nsView9.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView9.add(_nsTextField0);
        _nsButton0.setSize(85, 26);
        _nsButton0.setLocation(252, 168);
        ((EOViewLayout)_nsView9.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView9.add(_nsButton0);
        _nsButton12.setSize(85, 26);
        _nsButton12.setLocation(12, 168);
        ((EOViewLayout)_nsView9.getLayout()).setAutosizingMask(_nsButton12, EOViewLayout.MinYMargin);
        _nsView9.add(_nsButton12);
        _nsImageView2.setSize(80, 80);
        _nsImageView2.setLocation(10, 73);
        ((EOViewLayout)_nsView9.getLayout()).setAutosizingMask(_nsImageView2, EOViewLayout.MinYMargin);
        _nsView9.add(_nsImageView2);
        _nsTextField15.setSize(110, 56);
        _nsTextField15.setLocation(93, 85);
        ((EOViewLayout)_nsView9.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.MinYMargin);
        _nsView9.add(_nsTextField15);
        _nsView9.setSize(346, 204);
        _eoFrame0.setTitle("Register");
        _eoFrame0.setLocation(685, 590);
        _eoFrame0.setSize(346, 204);
    }
}
