// _Preview_EOArchive.java
// Generated by EnterpriseObjects palette at Thursday, August 30, 2007 11:48:51 PM America/New_York

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _Preview_EOArchive extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOView _qCRenderView0, _qCView0;
    javax.swing.JPanel _nsView0;

    public _Preview_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _qCRenderView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _qCView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
    }

    protected void _init() {
        super._init();
        if (!(_qCView0.getLayout() instanceof EOViewLayout)) { _qCView0.setLayout(new EOViewLayout()); }
        _qCRenderView0.setSize(347, 260);
        _qCRenderView0.setLocation(0, 0);
        ((EOViewLayout)_qCView0.getLayout()).setAutosizingMask(_qCRenderView0, EOViewLayout.MinYMargin);
        _qCView0.add(_qCRenderView0);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _qCView0.setSize(347, 260);
        _qCView0.setLocation(-7, -6);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_qCView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_qCView0);
        _nsView0.setSize(333, 248);
        _eoFrame0.setTitle("DM2 Status");
        _eoFrame0.setLocation(615, 327);
        _eoFrame0.setSize(333, 248);
    }
}
